version: 2.1

references:

  ## Docker image configuration

  config: &config
    working_directory: ~/workspace
    docker:
      - image: ayltai/hkvpn-infrastructure:latest
    environment:
      TERM: dumb

  configure_terraform: &configure_terraform
    - run:
        name: Configure credentials for accessing Terraform Cloud backend
        command: echo $TERRAFORM_TOKEN | base64 -di > ~/.terraformrc

  export_ssh_private_key: &export_ssh_private_key
    - run:
        name: Create .ssh directory to store keys
        command: mkdir ~/.ssh
    - run:
        name: Configure SSH private key for accessing the system to be provisioned
        command: echo $SSH_PRIVATE_KEY | base64 -di > ~/.ssh/hkvpn.key
    - run:
        name: Change SSH private key permission
        command: chmod 400 ~/.ssh/hkvpn.key

  export_ssh_public_key: &export_ssh_public_key
    - run:
        name: Configure SSH public key for accessing the system to be provisioned
        command: echo $SSH_PUBLIC_KEY | base64 -di > ~/.ssh/hkvpn.pub
    - run:
        name: Change SSH public key permission
        command: chmod 400 ~/.ssh/hkvpn.pub

  export_vault_password: &export_vault_password
    - run:
        name: Create Ansible Vault password file
        command: echo $VAULT_PASSWORD_FILE | base64 -di > ~/vault.pass
jobs:

  check:
    <<: *config
    steps:
      - checkout
      - run:
          name: Check if Terraform scripts are properly formatted
          command: terraform fmt -check -write=false
          working_directory: terraform
      - run:
          name: Lint Ansible scripts
          command: ansible-lint ./playbook.yml
          working_directory: ansible

  deploy_digitalocean:
    <<: *config
    steps:
      - checkout
      <<: *configure_terraform
      <<: *export_ssh_private_key
      <<: *export_ssh_public_key
      <<: *export_vault_password
      - run:
          name: Initialize Terraform backend and plugins
          command: echo 1 | terraform init
          working_directory: terraform-digitalocean
      - run:
          name: Validate the syntax of Terraform scripts
          command: terraform validate
          working_directory: terraform-digitalocean
      - run:
          name: Plan for the changes
          command: terraform plan -out main
          working_directory: terraform-digitalocean
      - run:
          name: Apply the changes
          command: terraform apply main
          working_directory: terraform-digitalocean
          no_output_timeout: 60m
      - store_artifacts:
          path: ~/hkvpn.ovpn
          destination: hkvpn.ovpn

  deploy_ec2:
    <<: *config
    steps:
      - checkout
      <<: *configure_terraform
      <<: *export_ssh_private_key
      <<: *export_ssh_public_key
      <<: *export_vault_password
      - run:
          name: Initialize Terraform backend and plugins
          command: echo 1 | terraform init
          working_directory: terraform-ec2
      - run:
          name: Validate the syntax of Terraform scripts
          command: terraform validate
          working_directory: terraform-ec2
      - run:
          name: Plan for the changes
          command: terraform plan -out main
          working_directory: terraform-ec2
      - run:
          name: Apply the changes
          command: terraform apply main
          working_directory: terraform-ec2
          no_output_timeout: 60m
      - store_artifacts:
          path: ~/hkvpn.ovpn
          destination: hkvpn.ovpn

  deploy_lightsail:
    <<: *config
    steps:
      - checkout
      <<: *configure_terraform
      <<: *export_ssh_private_key
      <<: *export_ssh_public_key
      <<: *export_vault_password
      - run:
          name: Initialize Terraform backend and plugins
          command: echo 1 | terraform init
          working_directory: terraform-lightsail
      - run:
          name: Validate the syntax of Terraform scripts
          command: terraform validate
          working_directory: terraform-lightsail
      - run:
          name: Plan for the changes
          command: terraform plan -out main
          working_directory: terraform-lightsail
      - run:
          name: Apply the changes
          command: terraform apply main
          working_directory: terraform-lightsail
          no_output_timeout: 60m
      - store_artifacts:
          path: ~/hkvpn.ovpn
          destination: hkvpn.ovpn

  deploy_azure:
    <<: *config
    steps:
      - checkout
      <<: *configure_terraform
      <<: *export_ssh_private_key
      <<: *export_ssh_public_key
      <<: *export_vault_password
      - run:
          name: Initialize Terraform backend and plugins
          command: echo 1 | terraform init
          working_directory: terraform-azure
      - run:
          name: Validate the syntax of Terraform scripts
          command: terraform validate
          working_directory: terraform-azure
      - run:
          name: Plan for the changes
          command: terraform plan -out main
          working_directory: terraform-azure
      - run:
          name: Apply the changes
          command: terraform apply main
          working_directory: terraform-azure
          no_output_timeout: 60m
      - store_artifacts:
          path: ~/hkvpn.ovpn
          destination: hkvpn.ovpn

  deploy_oracle:
    <<: *config
    steps:
      - checkout
      <<: *configure_terraform
      <<: *export_ssh_private_key
      - run:
          name: Configure API private key for provisioning the system
          command: echo $API_PRIVATE_KEY | base64 -di > ~/.ssh/hkvpn.pem
      - run:
          name: Change API private key permission
          command: chmod 400 ~/.ssh/hkvpn.pem
      <<: *export_vault_password
      - run:
          name: Initialize Terraform backend and plugins
          command: echo 1 | terraform init
          working_directory: terraform-oracle
      - run:
          name: Validate the syntax of Terraform scripts
          command: terraform validate
          working_directory: terraform-oracle
      - run:
          name: Plan for the changes
          command: terraform plan -out main
          working_directory: terraform-oracle
      - run:
          name: Apply the changes
          command: terraform apply main
          working_directory: terraform-oracle
          no_output_timeout: 60m
      - store_artifacts:
          path: ~/hkvpn.ovpn
          destination: hkvpn.ovpn

workflows:
  version: 2
  workflow:
    jobs:
      - check
      - approve_digitalocean:
          type: approval
          requires:
            - check
      - approve_ec2:
          type: approval
          requires:
            - check
      - approve_lightsail:
          type: approval
          requires:
            - check
      - approve_azure:
          type: approval
          requires:
            - check
      - approve_oracle:
          type: approval
          requires:
            - check
      - deploy_digitalocean:
          requires:
            - check
            - approve_digitalocean
          filters:
            branches:
              only:
                - master
      - deploy_ec2:
          requires:
            - check
            - approve_ec2
          filters:
            branches:
              only:
                - master
      - deploy_lightsail:
          requires:
            - check
            - approve_lightsail
          filters:
            branches:
              only:
                - master
      - deploy_azure:
          requires:
            - check
            - approve_azure
          filters:
            branches:
              only:
                - master
      - deploy_oracle:
          requires:
            - check
            - approve_oracle
          filters:
            branches:
              only:
                - master
