---
- name: Restart OpenVPN
  become: true
  systemd:
    name: openvpn@server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Restart Dnsmasq
  become: true
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
