---
- name: Set timezone
  become: true
  timezone:
    name: Asia/Hong_Kong

- name: Change number of open files limit
  become: true
  pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 64000

- name: Change number of processes limit
  become: true
  pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nproc
    value: 64000
