---
- name: Install prerequisites
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: yes
    upgrade: dist
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gzip
      - unzip
      - curl
      - wget
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Install Ubuntu LivePatch
  become: true
  snap:
    name: canonical-livepatch
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Enable Ubuntu LivePatch service
  become: true
  command: "canonical-livepatch enable {{ ubuntu_livepatch_key }}"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
    - ubuntu_livepath_enabled
