---
- name: setup
  hosts: hkvpn
  become: true
  tasks:
    - name: initialize
      include_role:
        name: initialize
    - name: openvpn
      include_role:
        name: openvpn
    - name: fail2ban
      include_role:
        name: fail2ban
    - name: instrumental
      include_role:
        name: instrumental
    - name: cleanup
      include_role:
        name: cleanup
