---
- name: Configure IP forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Add firewall before content
  become: true
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    content: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s 10.8.0.0/8 -o {{ network_interface }} -j MASQUERADE
      COMMIT

- name: Configure firewall forwarding policy
  become: true
  lineinfile:
    path: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY=\"DROP\""
    line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\""

- name: Open firewall ports for OpenVPN and SSH
  become: true
  shell: ufw allow openvpn && ufw allow OpenSSH

- name: Enable firewall
  become: true
  shell: ufw --force enable
  notify:
    - Restart OpenVPN
